Repository algosup/2023-2024-project-4-SPORTSHIELD-team-4, pull requests merged in 2024-03, with the labels that each got.

#4 Add template for documentation report.
  documents/.github/ISSUE_TEMPLATE/Documentation-issues.yml
  documents/FunctionalSpecifications/FunctionalSpecifications.md
  documents/QA/TestPlan.md
  documents/TechnicalSpecification/Images/BatteryFlow.png
  documents/TechnicalSpecification/TechnicalSpecifications.md
  documents/management/management_artifact.md
  documents/management/management_artifact/RACI.md
  documents/management/management_artifact/project_charter.md
  documents/management/management_artifact/team_code_of_conduct.md
  documents/management/weekly_reports/week_1.md
Labels: documentation, enhancement

#5 Move of the .github from document to dev
  .github/ISSUE_TEMPLATE/Bug-issues.yml
  .github/ISSUE_TEMPLATE/Documentation-issues.yml
  documents/management/management_artifact/RACI.md
  documents/management/management_artifact/pictures/alexis.png
  documents/management/management_artifact/pictures/habi.png
  documents/management/management_artifact/pictures/lucas.png
  documents/management/management_artifact/pictures/maxime.png
  documents/management/management_artifact/pictures/paul.png
  documents/management/management_artifact/pictures/raci.png
  documents/management/management_artifact/pictures/wilfried.png
  documents/management/management_artifact/project_charter.md
  documents/management/management_artifact/team_code_of_conduct.md
Labels: enhancement

#6 Move of the .github from Dev to main.
  .github/ISSUE_TEMPLATE/Bug-issues.yml
  .github/ISSUE_TEMPLATE/Documentation-issues.yml
  documents/FunctionalSpecifications/FunctionalSpecifications.md
  documents/QA/TestPlan.md
  documents/TechnicalSpecification/Images/BatteryFlow.png
  documents/TechnicalSpecification/TechnicalSpecifications.md
  documents/management/management_artifact.md
  documents/management/management_artifact/pictures/alexis.png
  documents/management/management_artifact/pictures/habi.png
  documents/management/management_artifact/pictures/lucas.png
  documents/management/management_artifact/pictures/maxime.png
  documents/management/management_artifact/pictures/paul.png
  documents/management/management_artifact/pictures/raci.png
  documents/management/management_artifact/pictures/wilfried.png
  documents/management/management_artifact/project_charter.md
  documents/management/management_artifact/team_code_of_conduct.md
  documents/management/weekly_reports/week_1.md
Labels: enhancement

#7 Correction of few issue on the code to able it to work in the github issue.
  .github/ISSUE_TEMPLATE/Bug-issues.yml
  .github/ISSUE_TEMPLATE/Documentation-issues.yml
  documents/TechnicalSpecification/TechnicalSpecifications.md
Labels: enhancement

#8 same correction but from dev to main.
  .github/ISSUE_TEMPLATE/Bug-issues.yml
  .github/ISSUE_TEMPLATE/Documentation-issues.yml
  documents/TechnicalSpecification/TechnicalSpecifications.md
Labels: enhancement

#10 Corrections of the issue template.
  .github/ISSUE_TEMPLATE/Bug-issues.yml
  .github/ISSUE_TEMPLATE/Documentation-issues.yml
Labels: enhancement

#11 Correction of the dropdown
  .github/ISSUE_TEMPLATE/Bug-issues.yml
  .github/ISSUE_TEMPLATE/Documentation-issues.yml
Labels: enhancement

#12 Document
  .github/ISSUE_TEMPLATE/Bug-issues.yml
  .github/ISSUE_TEMPLATE/Documentation-issues.yml
  documents/TechnicalSpecification/Images/Battery.png
  documents/TechnicalSpecification/Images/Buzzer.png
  documents/TechnicalSpecification/Images/ElectroMagnet.png
  documents/TechnicalSpecification/Images/ElectronicConfiguration.png
  documents/TechnicalSpecification/Images/ModuleGPS-removebg-preview.png
  documents/TechnicalSpecification/Images/NFCReader.png
  documents/TechnicalSpecification/Images/Sim.png
  documents/TechnicalSpecification/Images/XiaoBLE.png
  documents/TechnicalSpecification/TechnicalSpecifications.md
Labels: enhancement

#13 Changes in the issue template document.
  .github/ISSUE_TEMPLATE/Bug-issues.yml
  .github/ISSUE_TEMPLATE/Documentation-issues.yml
Labels: enhancement

#14 Trying to fix the template issue
  .github/ISSUE_TEMPLATE/Documentation-issues.yml
Labels: enhancement

#15 Final fix of all the issue in the issue template.
  .github/ISSUE_TEMPLATE/Bug-issues.yml
  .github/ISSUE_TEMPLATE/Documentation-issues.yml
  documents/TechnicalSpecification/TechnicalSpecifications.md
Labels: enhancement

#16 Creation of the pull request template.
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  documents/TechnicalSpecification/TechnicalSpecifications.md
  documents/management/management_artifact.md
  documents/management/weekly_reports/week_1.md
  documents/management/weekly_reports/weekly_reports.md
Labels: enhancement

#25 Technical Pull request
  .gitignore
  README.md
  documents/OperatorManual/OperatorManual.md
  documents/TechnicalSpecification/Images/AlarmManagementFlow.png
  documents/TechnicalSpecification/Images/BluetoothFlow.png
  documents/TechnicalSpecification/Images/GPSFlow.png
  documents/TechnicalSpecification/Images/ModuleGPS.png
  documents/TechnicalSpecification/Images/SimultaneousActionsFlow.png
  documents/TechnicalSpecification/TechnicalSpecifications.md
  documents/management/management_artifact/project_charter.md
Labels: documentation

#26 Update management document
  .github/ISSUE_TEMPLATE/Bug-issues.yml
  .github/ISSUE_TEMPLATE/Documentation-issues.yml
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .gitignore
  Documents/FunctionalSpecifications/FunctionalSpecifications.md
  Documents/Management/ManagementArtifacts.md
  Documents/Management/ManagementArtifacts/Pictures/alexis.png
  Documents/Management/ManagementArtifacts/Pictures/habi.png
  Documents/Management/ManagementArtifacts/Pictures/lucas.png
  Documents/Management/ManagementArtifacts/Pictures/maxime.png
  Documents/Management/ManagementArtifacts/Pictures/paul.png
  Documents/Management/ManagementArtifacts/Pictures/raci.png
  Documents/Management/ManagementArtifacts/Pictures/wilfried.png
  Documents/Management/ManagementArtifacts/ProjectCharter.md
  Documents/Management/ManagementArtifacts/TeamCodeOfConduct.md
  Documents/Management/WeeklyReports/Week1.md
  Documents/Management/WeeklyReports/Week2.md
  Documents/Management/WeeklyReports/WeeklyReports.md
  Documents/OperatorManual/OperatorManual.md
  Documents/QA/TestPlan.md
  Documents/TechnicalSpecification/Images/AlarmManagementFlow.png
  Documents/TechnicalSpecification/Images/Battery.png
  Documents/TechnicalSpecification/Images/BatteryFlow.png
  Documents/TechnicalSpecification/Images/BluetoothFlow.png
  Documents/TechnicalSpecification/Images/Buzzer.png
  Documents/TechnicalSpecification/Images/ElectroMagnet.png
  Documents/TechnicalSpecification/Images/ElectronicConfiguration.png
  Documents/TechnicalSpecification/Images/GPSFlow.png
  Documents/TechnicalSpecification/Images/ModuleGPS.png
  Documents/TechnicalSpecification/Images/NFCReader.png
  Documents/TechnicalSpecification/Images/Sim.png
  Documents/TechnicalSpecification/Images/SimultaneousActionsFlow.png
  Documents/TechnicalSpecification/Images/XiaoBLE.png
  Documents/TechnicalSpecification/TechnicalSpecifications.md
  README.md
  documents/TechnicalSpecification/TechnicalSpecifications.md
  documents/management/management_artifact.md
  documents/management/weekly_reports/week_1.md
Labels: documentation

#27 Typo checked in the Technical
  documents/TechnicalSpecification/TechnicalSpecifications.md
Labels: documentation, typo

#28 Dev
  Documents/FunctionalSpecifications/FunctionalSpecifications.md
  Documents/Management/ManagementArtifacts.md
  Documents/Management/ManagementArtifacts/Pictures/alexis.png
  Documents/Management/ManagementArtifacts/Pictures/habi.png
  Documents/Management/ManagementArtifacts/Pictures/lucas.png
  Documents/Management/ManagementArtifacts/Pictures/maxime.png
  Documents/Management/ManagementArtifacts/Pictures/paul.png
  Documents/Management/ManagementArtifacts/Pictures/raci.png
  Documents/Management/ManagementArtifacts/Pictures/wilfried.png
  Documents/Management/ManagementArtifacts/ProjectCharter.md
  Documents/Management/ManagementArtifacts/TeamCodeOfConduct.md
  Documents/Management/WeeklyReports/Week1.md
  Documents/Management/WeeklyReports/Week2.md
  Documents/Management/WeeklyReports/WeeklyReports.md
  Documents/OperatorManual/OperatorManual.md
  Documents/QA/TestPlan.md
  Documents/TechnicalSpecification/Images/AlarmManagementFlow.png
  Documents/TechnicalSpecification/Images/Battery.png
  Documents/TechnicalSpecification/Images/BatteryFlow.png
  Documents/TechnicalSpecification/Images/BluetoothFlow.png
  Documents/TechnicalSpecification/Images/Buzzer.png
  Documents/TechnicalSpecification/Images/ElectroMagnet.png
  Documents/TechnicalSpecification/Images/ElectronicConfiguration.png
  Documents/TechnicalSpecification/Images/GPSFlow.png
  Documents/TechnicalSpecification/Images/ModuleGPS.png
  Documents/TechnicalSpecification/Images/NFCReader.png
  Documents/TechnicalSpecification/Images/Sim.png
  Documents/TechnicalSpecification/Images/SimultaneousActionsFlow.png
  Documents/TechnicalSpecification/Images/XiaoBLE.png
  Documents/TechnicalSpecification/TechnicalSpecifications.md
  documents/management/weekly_reports/weekly_reports.md
Labels: documentation

#30 Battery optimisation
  .gitignore
  Code/SPORTSHIELD.ino
Labels: enhancement

#31 First version of the product
  .gitignore
  Code/SPORTSHIELD.ino
Labels: enhancement

#33 Implementation of the battery management
  Code/SPORTSHIELD/SPORTSHIELD.ino
  Code/SPORTSHIELD/battery.h
  Code/SPORTSHIELD/globalVar.h
  Code/SPORTSHIELD/struct.h
Labels: enhancement

#34 Implementation of the battery management
  Code/SPORTSHIELD/SPORTSHIELD.ino
  Code/SPORTSHIELD/battery.h
  Code/SPORTSHIELD/globalVar.h
  Code/SPORTSHIELD/struct.h
Labels: enhancement

#36 Secure Bluetooth implementation
  .gitignore
  Code/SPORTSHIELD/SPORTSHIELD.ino
  Code/SPORTSHIELD/battery.h
  Code/SPORTSHIELD/bluetooth.h
  Code/SPORTSHIELD/globalVar.h
  Code/SPORTSHIELD/gps.h
  Code/SPORTSHIELD/imu.h
  Code/SPORTSHIELD/sim.h
  Code/SPORTSHIELD/struct.h
Labels: enhancement

#37 Merge the branch Document into Dev to update the readme.md file
  Documents/CodeDocumentation/NFC.md
  Documents/CodeDocumentation/batteryImprovement.md
  Documents/CodeDocumentation/secureBluetooth.md
  Documents/OperatorManual/OperatorManual.md
  Documents/TechnicalSpecification/Images/AlexisLASSELIN.png
  Documents/TechnicalSpecification/Images/Arduino-removebg-preview.png
  Documents/TechnicalSpecification/Images/C++_logo-removebg-preview.png
  Documents/TechnicalSpecification/Images/Clogo-removebg-preview.png
  Documents/TechnicalSpecification/Images/HabiCAILLEAU.png
  Documents/TechnicalSpecification/Images/LucasAUBARD.png
  Documents/TechnicalSpecification/Images/MaximeCARON.jpeg
  Documents/TechnicalSpecification/Images/PaulNOWAK.jpeg
  Documents/TechnicalSpecification/Images/WilfriedPORTET.png
  README.md
Labels: documentation

#38 Merge the dev branch into the main one to update the readme.md file
  Documents/CodeDocumentation/NFC.md
  Documents/CodeDocumentation/batteryImprovement.md
  Documents/CodeDocumentation/secureBluetooth.md
  Documents/OperatorManual/OperatorManual.md
  Documents/TechnicalSpecification/Images/AlexisLASSELIN.png
  Documents/TechnicalSpecification/Images/Arduino-removebg-preview.png
  Documents/TechnicalSpecification/Images/C++_logo-removebg-preview.png
  Documents/TechnicalSpecification/Images/Clogo-removebg-preview.png
  Documents/TechnicalSpecification/Images/HabiCAILLEAU.png
  Documents/TechnicalSpecification/Images/LucasAUBARD.png
  Documents/TechnicalSpecification/Images/MaximeCARON.jpeg
  Documents/TechnicalSpecification/Images/PaulNOWAK.jpeg
  Documents/TechnicalSpecification/Images/WilfriedPORTET.png
  README.md
Labels: documentation
